FROM n8nio/n8n:latest

ENV N8N_BASIC_AUTH_ACTIVE=false
ENV N8N_PORT=5678
ENV WEBHOOK_URL=https://n8n-zalk.onrender.com/
ENV N8N_SKIP_WEBHOOK_DEREGISTRATION=true
ENV N8N_HOST=0.0.0.0
ENV N8N_PROTOCOL=https

EXPOSE 5678

CMD ["tini", "--", "n8n"]
